UI_CONFIG:
  TITLE: 
    TEXT: "Snake Game"
    PADDING: 10
    FONT: 
      NAME: "Arial"
      SIZE: 16
      STYLE: bold
  CANVAS:
    BG: "white"
    FG: "black"
    BD: 0
    HIGHLIGHTTHICKNESS: 0
  SCORE:
    SIDE: LEFT
    PADDING: 20
    FONT:
      NAME: "Arial"
      SIZE: 12
      STYLE: italic
  LEGEND:
    SIDE: LEFT
    PADDING: 10
    FONT:
      NAME: "Arial"
      SIZE: 10
      STYLE: italic
  BOARD:
    FILL: "gray"
    DASH: (2, 2)
  SNAKE:
    HEAD:
      SYMBOL: 
        UP: "^"
        DOWN: "v"
        LEFT: "<"
        RIGHT: ">"
      FILL: "green"
      FONT:
        NAME: "Arial"
        SIZE: 6
        STYLE: bold
    BODY:
      SYMBOL: "*"
      FILL: "green"
      FONT:
        NAME: "Arial"
        SIZE: 4
        STYLE: bold
  FOOD:
    SIMPLE:
      SYMBOL: "O"
      FILL: "red"
      FONT:
        NAME: "Arial"
        SIZE: 6
        STYLE: bold
    SUPER:
      SYMBOL: "X"
      FILL: "purple"
      FONT:
        NAME: "Arial"
        SIZE: 6
        STYLE: bold
  GAME_OVER:
    TEXT: "GAME OVER"
    PADDING: 10
    FILL: "red"
    FONT:
      NAME: "Arial"
      SIZE: 24
      STYLE: bold

GAME_CONFIG:
  SLEEP_PER_TIMESTEP: 0.2
  BOARD_DIM: 11 # Must be an odd number
  EPISODES_PER_RENDER: 20
  FOOD:
    SUPERFOOD_PROBABILITY: 0.1
    SUPERFOOD_LIFETIME: 15
  SNAKE:
    SNAKE_INIT_LENGTH: 3 # Recommended to be between 3 and 5
    SNAKE_INIT_DIRECTION: RIGHT # Must be one of RIGHT, LEFT, UP or DOWN
    SNAKE_INIT_POS: (0,0) # SAMPLE - OVERWRITTEN LATER
  SCORE:
    EAT_FOOD: 10
    XPLIER_EAT_SUPERFOOD: 10
    
DATA_CONFIG:
  DATA_FOLDER_PATH: src/data
  GAME_DATA_FOLDER_NAME: gamedata
  HIGH_SCORE_FILE_NAME: high_score.txt
  SCORES_FILE_NAME: scores.txt
  MODEL_DATA_FOLDER_NAME: modeldata

LOGS_CONFIG:
  LOGS_FOLDER_PATH: logs

MODEL_CONFIG:
  MODELS_FOLDER_PATH: src/models
  MODEL_NAME_PREFIX: snake_model_
  IMAGE_INPUT_SIZE: 224 # SAMPLE - OVERWRITTEN LATER
  
TRAINING_CONFIG:
  REWARDS:
    EAT_FOOD: 10
    XPLIER_EAT_SUPERFOOD: 10
    COLLIDE: -100
    NOTHING: 0.1
    MOVE: -1
  MAX_TRAINING_EPISODES: 10000
  EPISODES_PER_CHECKPOINT: 100
  EXPLORATION_RATE: 0.999
  EXPLORATION_RATE_DECAY: 0.999
  EXPLORATION_RATE_MIN: 0
  LEARNING_RATE: 0.0001


