UI_CONFIG:
  CELL_SIZE_IN_PIXELS: 30
  EXTRA_WINDOW_HEIGHT: 100
  TITLE: 
    TEXT: "Snake Game"
    COLOUR: WHITE
    TOP_PADDING: 20
    FONT: 
      NAME: "Arial"
      SIZE: 16
  SCORE:
    COLOUR: WHITE
    BOTTOM_PADDING: 10
    FONT:
      NAME: "Arial"
      SIZE: 12
  FOOD_LABEL:
    COLOUR: WHITE
    BOTTOM_PADDING: 10
    FONT:
      NAME: "Arial"
      SIZE: 12
  FOOD:
    SIMPLE:
      SYMBOL: "O"
      FILL: RED
      FONT:
        NAME: "Arial"
        SIZE: 8
        COLOUR: WHITE
    SUPER:
      SYMBOL: "X"
      FILL: PURPLE
      FONT:
        NAME: "Arial"
        SIZE: 8
        COLOUR: WHITE
  BOARD:
    PADDING: 10
    FILL: BLACK
  SNAKE:
    HEAD:
      FILL: GREEN
      STRETCH: 8
    BODY:
      FILL: GREEN
  GAME_OVER_LABEL:
    TEXT: "GAME OVER"
    FILL: WHITE
    FONT:
      NAME: "Arial"
      SIZE: 24
      STYLE: bold
      COLOUR: RED

GAME_CONFIG:
  SLEEP_PER_TIMESTEP: 0.2
  BOARD_DIM: 11 # Must be an odd number
  EPISODES_PER_RENDER: 2
  FOOD:
    SUPERFOOD_PROBABILITY: 0.1
    SUPERFOOD_LIFETIME: 15
  SNAKE:
    SNAKE_INIT_LENGTH: 3 # Recommended to be between 3 and 5
    SNAKE_INIT_DIRECTION: RIGHT # Must be one of RIGHT, LEFT, UP or DOWN
    SNAKE_INIT_POS: (0,0) # SAMPLE - AUTOCALCULATED & OVERWRITTEN LATER
  SCORE:
    EAT_FOOD: 10
    XPLIER_EAT_SUPERFOOD: 10
    
DATA_CONFIG:
  DATA_FOLDER_PATH: src/data
  GAME_DATA_FOLDER_NAME: gamedata
  HIGH_SCORE_FILE_NAME: high_score.txt
  SCORES_FILE_NAME: scores.txt
  MODEL_DATA_FOLDER_NAME: modeldata

LOGS_CONFIG:
  LOGS_FOLDER_PATH: logs

MODEL_CONFIG:
  NUM_ACTIONS: 5
  MODELS_FOLDER_PATH: src/models
  MODEL_NAME_PREFIX: snake_model_
  IMAGE_INPUT_SIZE: (720, 1280) # SAMPLE - AUTOCALCULATED & OVERWRITTEN LATER
  
TRAINING_CONFIG:
  REWARDS:
    EAT_FOOD: 10
    XPLIER_EAT_SUPERFOOD: 10
    COLLIDE: -100
    NOTHING: 0.1
    MOVE: -1
  MAX_TRAINING_EPISODES: 10 # Change during actual PROD
  MAX_TIMESTEPS_PER_EPISODE: 100 # Change during actual PROD
  EPISODES_PER_CHECKPOINT: 100
  LEARNING_RATE: 0.0001
  REPLAY_MEMORY_SIZE: 500
  GAMMA: 0.99
  EPSILON_START: 1.0
  EPSILON_END: 0.01
  EPSILON_DECAY: 0.995
  TARGET_UPDATE_FREQUENCY: 10
  BATCH_SIZE: 64
  


