GAME_CONFIG:
  SLEEP_PER_TIMESTEP: 0.2
  BOARD_DIM: 11
  EPISODES_PER_RENDER: 20
  FOOD:
    SUPERFOOD_PROBABILITY: 0.1
    SUPERFOOD_LIFETIME: 15
  SNAKE:
    SNAKE_INIT_LENGTH: 3
    SNAKE_INIT_DIRECTION: RIGHT
  SCORE:
    EAT_FOOD: 10
    XPLIER_EAT_SUPERFOOD: 10
    
DATA_CONFIG:
  DATA_FOLDER_PATH: src/data
  GAME_DATA_FOLDER: gamedata
  MODEL_DATA_FOLDER: modeldata

LOGS_CONFIG:
  LOGS_FOLDER_PATH: logs

MODEL_CONFIG:
  MODELS_FOLDER_PATH: src/models
  MODEL_NAME_PREFIX: snake_model_
  LEARNING_RATE: 0.0001
  OPTIMIZER: Adam
  NUM_ACTIONS: 5

TRAINING_CONFIG:
  REWARDS:
    RW_EAT_FOOD: 10
    RW_XPLIER_EAT_SUPERFOOD: 10
    RW_COLLIDE: -100
    RW_NOTHING: 0.1
    RW_MOVE: -1
  MAX_TRAINING_EPISODES: 10000
  EPISODES_PER_CHECKPOINT: 100
  EXPLORATION_RATE: 0.999
  EXPLORATION_RATE_DECAY: 0.999
  EXPLORATION_RATE_MIN: 0

