UI_CONFIG:
  CELL_SIZE_IN_PIXELS: 30
  EXTRA_WINDOW_HEIGHT: 100
  BG_COLOUR: "BLACK"
  TITLE: 
    TEXT: "Snake Game"
    COLOUR: "WHITE"
    TOP_PADDING: 20
    FONT: 
      NAME: Arial
      SIZE: 16
  SCORE:
    SECTION_HEIGHT: 40
    COLOUR: "WHITE"
    BOTTOM_PADDING: 10
    FONT:
      NAME: Arial
      SIZE: 12
  FOOD_LABEL:
    COLOUR: "WHITE"
    BOTTOM_PADDING: 10
    FONT:
      NAME: Arial
      SIZE: 12
  FOOD:
    SIMPLE:
      SYMBOL: "O"
      FILL: "RED"
      FONT:
        NAME: Arial
        SIZE: 8
        COLOUR: "WHITE"
    SUPER:
      SYMBOL: "X"
      FILL: "PURPLE"
      FONT:
        NAME: Arial
        SIZE: 8
        COLOUR: "WHITE"
  BOARD:
    PADDING: 10
    FILL: "BLACK"
    BORDER:
      FILL: "WHITE"
      THICKNESS: 3
    GRID:
      FILL: "TRANSPARENT_GREY"
      THICKNESS: 1
  SNAKE:
    HEAD:
      FILL: "GREEN"
      STRETCH: -1
    BODY:
      FILL: "GREEN"
      STRETCH: -2
  GAME_OVER_LABEL:
    TEXT: "GAME OVER"
    FILL: "WHITE"
    FONT:
      NAME: Arial
      SIZE: 24
      STYLE: bold
      COLOUR: "RED"

GAME_CONFIG:
  SLEEP_PER_TIMESTEP: 0.2
  BOARD_DIM: 20
  EPISODES_PER_RENDER: 5
  FOOD:
    SUPERFOOD_PROBABILITY: 0.1
    SUPERFOOD_LIFETIME: 15
  SNAKE: # Recommended NOT to change
    SNAKE_INIT_LENGTH: 3 # Recommended to be between 3 and 5
    SNAKE_INIT_DIRECTION: "RIGHT" # Must be one of RIGHT, LEFT, UP or DOWN
    SNAKE_INIT_POS: [10,10]
  SCORE:
    EAT_FOOD: 10.0
    XPLIER_EAT_SUPERFOOD: 10.0
    
DATA_CONFIG:
  DATA_FOLDER_PATH: "src/data"
  MODEL_DATA_FOLDER_PATH: "src/data/modeldata"
  GAME_DATA_FOLDER_PATH: "src/data/gamedata"
  HIGH_SCORE_FILE_PATH: "src/data/high_score.txt"
  SCORES_FILE_PATH: "src/data/scores.txt"

LOGS_CONFIG:
  LOGS_FOLDER_PATH: "logs"

MODEL_CONFIG:
  NUM_ACTIONS: 5
  MODELS_FOLDER_PATH: "src/models"
  MODEL_NAME_PREFIX: "snake_model_"
  IMAGE_INPUT_SIZE: [600, 600] # SAMPLE - AUTOCALCULATED & OVERWRITTEN LATER
  
TRAINING_CONFIG:
  REWARDS:
    EAT_FOOD: 10.0
    XPLIER_EAT_SUPERFOOD: 10.0
    COLLIDE: -100.0
    NOTHING: 0.1
    MOVE: -1.0
  MAX_TRAINING_EPISODES: 10 # Change during actual PROD
  MAX_TIMESTEPS_PER_EPISODE: 100 # Change during actual PROD
  EPISODES_PER_CHECKPOINT: 2 # Change during actual PROD
  LEARNING_RATE: 0.0001
  REPLAY_MEMORY_SIZE: 500
  GAMMA: 0.99
  EPSILON_START: 1.0
  EPSILON_END: 0.01
  EPSILON_DECAY: 0.995
  TARGET_UPDATE_FREQUENCY: 10
  BATCH_SIZE: 64
  CLIP_GRADIENTS: 100
  PRINT_LOSS_EVERY: 50
  


