DATA_CONFIG:
  DATA_FOLDER_PATH: src/data

LOGS_CONFIG:
  LOGS_FOLDER_PATH: logs

MODEL_CONFIG:
  IMAGE_INPUT_SIZE: 22
  MODELS_FOLDER_PATH: src/models
  MODEL_NAME_PREFIX: snake_model_
  LEARNING_RATE: 0.0001
  OPTIMIZER: Adam
  NUM_ACTIONS: 4

TRAINING_CONFIG:
  REWARDS:
    RW_EAT_FOOD: 10
    RW_XPLIER_EAT_SUPERFOOD: 10
    RW_COLLIDE: -100
    RW_MOVE: -1
  MAX_TRAINING_EPISODES: 10000
  EPISODES_PER_CHECKPOINT: 100
  EXPLORATION_RATE: 0.999
  EXPLORATION_RATE_DECAY: 0.999
  EXPLORATION_RATE_MIN: 0.01

GAME_CONFIG:
  SLEEP_PER_TIMESTEP: 0.2
  BOARD_WIDTH: 20
  BOARD_HEIGHT: 20
  EPISODES_PER_RENDER: 20
  FOOD:
    SUPERFOOD_PROBABILITY: 0.1
    SUPERFOOD_LIFETIME: 15
  SNAKE:
    SNAKE_INIT_POS: (5, 5)
    SNAKE_INIT_LENGTH: 3
    SNAKE_INIT_DIRECTION: RIGHT
  SCORE:
    EAT_FOOD: 10
    XPLIER_EAT_SUPERFOOD: 10